spring.application.name=enviosExpress

spring.datasource.url=jdbc:postgresql://localhost:5433/envios-express
spring.datasource.username=postgres
spring.datasource.password=1998

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

# Para que CXF exponga el endpoint en /services/*
server.servlet.context-path=/
